/* APP */
export const SET_ROUTES_POWERS = 'SET_ROUTES_POWERS';
export const SET_LOADED_ROUTES_POWERS = 'SET_LOADED_ROUTES_POWERS';
export const SET_ROLES = 'SET_ROLES';
export const SET_LOADED_ROLES = 'SET_LOADED_ROLES';
export const REMOVE_ALL_ROLES = 'REMOVE_ALL_ROLES';
export const SET_ACTIVE_ROLE = 'SET_ACTIVE_ROLE';
export const REMOVE_ALL_ROUTE_POWERS = 'REMOVE_ALL_ROUTE_POWERS';
